# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '30 9-16 * * 6,0'
    - cron: '20 12-22 * * 1-5'
    - cron: '10 3-11 4-20 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  auto_report:
    # The type of runner that the job will run on
    name: 'Auto counting and push the change to my repo'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create sample file with just timestamp
        run: date +%s >> counting.txt

      - name: Commit file
        run: |
          git config --global user.name 'Cong Automated Counting'
          git config --global user.email '15138747+congthanhng@users.noreply.github.com'
          git add counting.txt
          git commit -am "Automated counting"
          git push
