# This is a basic workflow to help you get started with Actions

name: Counting Report

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '42 10,16 * * 6,0'
    - cron: '11 15-21 * * 1-5'
    - cron: '08 12-14 14-21 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto_report:
    name: 'Auto counting and push the change to my repo'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create sample file with just timestamp
      run: date +%s >> counting.txt
    - name: Commit file
      run: |
        git config --global user.name 'Cong Automated Counting'
        git config --global user.email '15138747+congthanhng@users.noreply.github.com'
        git add counting.txt
        git commit -am "Automated counting"
        git push
