# This is a basic workflow to help you get started with Actions

name: Record Time

# Controls when the workflow will run
on:
  schedule:
    - cron: '11 8-12 * * 2,4,6'
    - cron: '35 13-19 * * 0,3,5'
    
jobs:
  auto_record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create sample file with just timestamp
        run: date "+%D - %T" >> record.txt
        
      # Runs a set of commands using the runners shell
      - name: Commit file
        run: |
          git config --global user.name 'Cong automated record'
          git config --global user.email '15138747+congthanhng@users.noreply.github.com'
          git add record.txt
          git commit -am "Automated record"
          git push
