# This is a basic workflow to help you get started with Actions

name: Record Time

# Controls when the workflow will run
on:
  schedule:
    - cron: '30 9-16 * * 6,0'
    - cron: '8,16,24,32,40,48,54 1-23 * * 1-5'
    
jobs:
  auto_record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create sample file with just timestamp
        run: date +%s time +%s >> record.txt
        
      # Runs a set of commands using the runners shell
      - name: Commit file
        run: |
          git config --global user.name 'Cong automated record'
          git config --global user.email '15138747+congthanhng@users.noreply.github.com'
          git add record.txt
          git commit -am "Automated record"
          git push
